### ISSUE TITLE
Named export 'useToast' not found

### ISSUE THREAD

**Issue by ilrein** [ankurk91/vue-toast-notification#78]
**I'm submitting a ...**  (check one with "x")

```
[ X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* "nuxt": "^3.0.0-rc.9"
* This package version : "vue-toastification": "^2.0.0-rc.5"

**Current behavior**
It works fine when developing locally, but when building for prod `nuxt generate` it throws an error:

```
[nuxt] [request error] [unhandled] [500] Named export 'useToast' not found. The requested module 'file:///Users/ilia/condobeaver3/node_modules/vue-toastification/dist/index.cjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///Users/ilia/condobeaver3/node_modules/vue-toastification/dist/index.cjs';
const { useToast } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-toast-notification/issues/58

**Comment by dev-caballero** [comment]
> #58

This is for another library, this is happening to me as well with `vue-toastification@2.0.0-rc.5`

```
20|congres |   at Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
20|congres | [nuxt] [request error] [unhandled] [500] Named export 'useToast' not found. The requested module 'vue-toastification' is a CommonJS module, which may not support all module.exports as named exports.
20|congres | CommonJS modules can always be imported via the default export, for example using:
20|congres | 
20|congres | import pkg from 'vue-toastification';
20|congres | const { useToast } = pkg;
20|congres | 
20|congres |   at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)  
20|congres |   at ModuleJob.run (internal/modules/esm/module_job.js:179:5)  
20|congres |   at Loader.import (internal/modules/esm/loader.js:178:24)  
20|congres |   at ./node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs:16:24  
20|congres |   at ./node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs:91:91  
20|congres |   at ./node_modules/nitropack/dist/runtime/renderer.mjs:10:22  
20|congres |   at ./.output/server/node_modules/h3/dist/index.mjs:592:19  
20|congres |   at Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
```
